name: Deploy Namadillo
on: 
  workflow_dispatch

env:
  INDEXER_URL: https://indexer.public.heliax.work/internal-devnet-43.35fd77a4447
  RPC_URL: https://proxy.public.heliax.work/internal-devnet-43.35fd77a4447
  CHAIN_ID: internal-devnet-43.35fd77a4447
  CI: false

jobs:
  build:
    name: Build and deploy Namadillo and extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yarn dependencies
        uses: ./.github/actions/yarn-cache

      - name: Restore Rust cache
        uses: ./.github/actions/rust-cache
        with:
          cache-name: build

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Build Namadillo
        working-directory: ./apps/namadillo
        run: yarn build

      - name: Configure Namadillo
        working-directory: ./apps/namadillo
        run: |
          echo "" > dist/config.toml
          echo "indexer_url = \"${{ env.INDEXER_URL }}\"" >> dist/config.toml
          echo "rpc_url = \"${{ env.RPC_URL }}\"" >> dist/config.toml

      - name: Build the Chrome extension
        working-directory: ./apps/extension
        run: yarn build:chrome
        env:
          NAMADA_INTERFACE_NAMADA_CHAIN_ID: ${{ env.CHAIN_ID }}

      - name: Build the Firefox extension
        working-directory: ./apps/extension
        run: yarn build:firefox
        env:
          NAMADA_INTERFACE_NAMADA_CHAIN_ID: ${{ env.CHAIN_ID }}

      - name: Copy the extensions for deployment
        run: |
          cp apps/extension/build/firefox/namada_keychain-*.zip apps/namadillo/dist/namada-keychain-firefox.zip
          cp apps/extension/build/chrome/namada_keychain-*.zip apps/namadillo/dist/namada-keychain-chrome.zip

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:shield-crypto/namadillo-build.git
          BRANCH: main
          FOLDER: "./apps/namadillo/dist"
          SSH_PRIVATE_KEY: ${{ secrets.GH_DEPLOY_KEY }}
